package:
  name: py3-httptools
  version: 0.6.4
  epoch: 0
  description: Python binding for the nodejs HTTP parser
  annotations:
    cgr.dev/ecosystem: python
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: httptools

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - llhttp-dev
      - py3-supported-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e265ae033d3d7212f92a614963a349e315f82df3
      recurse-submodules: true
      repository: https://github.com/MagicStack/httptools
      tag: v${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: MagicStack/httptools
    strip-prefix: v
    tag-filter: v
