package:
  name: py3-uvloop
  version: 0.21.0
  epoch: 0
  description: Ultra fast asyncio event loop.
  annotations:
    cgr.dev/ecosystem: python
  copyright:
    - license: Apache-2.0
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: uvloop

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - libtool
      - py3-supported-build-base-dev
      - py3-supported-cython

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2e8feae2a6db57bb611ffa388d28443487f4db94
      recurse-submodules: true
      repository: https://github.com/MagicStack/uvloop
      tag: v${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - name: Test basic functionality
          runs: python${{range.key}} test.py | grep "Hello, World!"

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  ignore-regex-patterns:
    - \.[a-z]+$
    - "[a-z]+[0-9]+$"
  github:
    identifier: MagicStack/uvloop
    strip-prefix: v
    tag-filter: v
